export const services = [
  { id: 1, slug: 'nervous-system-regulation', number: '01', name: 'Nervous System Regulation', eyebrow: 'ONE-TO-ONE COUNSELLING · THE FOUNDATION', description: 'A practical, personalised session for anxiety, anger, overthinking, sleep, family stress and repeating patterns.', format: '60–75 min live Zoom session', price: '₹2,500 / $55', for: 'Individual, couple, mother-child or family', receive: ['Complete nervous system pattern mapping', 'In-session regulation practices', 'A seven-day personalised ritual plan'] },
  { id: 2, slug: 'weekly-live-knowledge-session', number: '02', name: 'Weekly Live Knowledge Session', eyebrow: 'LIVE TEACHING · FOR BEGINNERS', description: 'A fixed-time weekly class that makes nervous system regulation simple, human and relevant to real life.', format: '60 min weekly Zoom class', price: '₹799/month or ₹199/class · $19/month', for: 'Anyone ready to begin in a group', receive: ['One deep topic every week', 'Live Q&A', 'Seven-day recording access'] },
  { id: 3, slug: 'core-transformation', number: '03', name: 'Core Transformation', eyebrow: 'COMPLETE BODY REWIRE & NERVOUS SYSTEM HEALING', description: 'Deeper work for past patterns, trauma, family imprints, karma, blocked energy and the body, mind and soul.', format: '2-day intensive or 4-week online program', price: '₹6,999 / ₹9,999 · $125', for: 'Group workshop or individual program', receive: ['Nervous system, subconscious and karmic pattern work', 'Morning, evening and sleep rituals', 'Practices designed for daily use'] },
  { id: 4, slug: 'power-of-sound-and-mantra', number: '04', name: 'Power of Sound & Mantra', eyebrow: 'MANTRA HEALING PROGRAM', description: 'Explore sound, vibration and spiritual practice as a pathway to regulation and a more present life.', format: '4-week online program', price: '₹4,999 · $89', for: 'Group program or individual work', receive: ['Live chanting sessions', 'Science and spirituality around sound', 'Eleven-minute mantra audios for lifetime use'] },
  { id: 5, slug: 'relationship-healing', number: '05', name: 'Relationship Healing', eyebrow: 'COUPLE & FAMILY HEALING', description: 'Understand co-regulation, co-triggering and the family patterns that shape how you relate.', format: '90 min deep relationship counselling on Zoom', price: '₹3,500 · $75', for: 'Individuals, couples and full families', receive: ['Relationship and family pattern mapping', 'Co-regulation practices', 'Tools for safety, love and understanding'] },
  { id: 6, slug: 'environment-regulation', number: '06', name: 'Environment Regulation', eyebrow: 'THE ENERGY OF YOUR SURROUNDINGS', description: 'Your rooms, light, sound, objects and rhythms are speaking to your nervous system every day.', format: '60 min live environment audit by video call', price: '₹2,000 · $45', for: 'Individuals and families', receive: ['A guided walkthrough of your space', 'Draining and supportive elements identified', 'Practical changes for more calm'] },
  { id: 7, slug: 'the-bridge', number: '07', name: 'The Bridge', eyebrow: 'REGULATION FOR SPIRITUAL GROWTH', description: 'A mentorship for bringing spiritual understanding into stress, relationships, responsibilities and ordinary life.', format: '6-week deep mentorship on Zoom', price: '₹25,000 · $333', for: 'Individual mentorship · limited seats', receive: ['Weekly one-to-one counselling', 'Voice-note support', 'Real-world practices for spiritual presence'] },
  { id: 8, slug: 'the-presence-room', number: '08', name: 'The Presence Room', eyebrow: 'DAILY HEALING · DAILY PRESENCE', description: 'Healing is not one session. It is the small, daily returns that teach your system a new way to be.', format: 'Ongoing group membership', price: '₹999/month · $21/month', for: 'Monthly or yearly group membership', receive: ['Daily practices, mantras and regulation tools', 'Two live calls every month', 'Breathwork, sound healing and mantra library'] },
] as const

export type StudioService = (typeof services)[number]
