import Link from 'next/link'
import { notFound } from 'next/navigation'
import { services } from '@/app/content/services'

export default async function ServiceDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const service = services.find((item) => item.slug === slug)
  if (!service) notFound()
  return <main className="service-detail"><header><p className="eyebrow">{service.eyebrow}</p><span className="service-detail-number">{service.number}</span><h1>{service.name}</h1><p>{service.description}</p><div className="service-detail-meta"><span>{service.format}</span><b>{service.price}</b></div><Link href={`/book?service=${service.id}`} className="button button--ink">Choose this support <span>↗</span></Link></header><section className="service-detail-body"><div><p className="eyebrow">WHO THIS MAY SUPPORT</p><h2>{service.for}</h2><p>This is a space for practical, personalised guidance. Your pace, circumstances and capacity are part of the work—not obstacles to it.</p></div><div><p className="eyebrow">WHAT YOU LEAVE WITH</p><ul>{service.receive.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className="service-faq"><p className="eyebrow">A FEW PRACTICAL QUESTIONS</p><h2>Before you book.</h2><details><summary>What happens after I choose a time?</summary><p>Your booking request is checked and a confirmation is sent to the email address you provide. Meeting details are shared in that confirmation when applicable.</p></details><details><summary>Do I need to know exactly what I need?</summary><p>No. You can bring what feels most present. The first conversation can help clarify whether this offering is the right fit.</p></details><details><summary>Is this medical or emergency support?</summary><p>No. Instayog sessions are supportive and reflective; they do not replace emergency, medical, diagnostic or crisis care.</p></details></section><section className="service-detail-cta"><p className="eyebrow">A CLEAR NEXT STEP</p><h2>You do not have to hold the whole journey at once.</h2><p>Start with a conversation about what is present for you now.</p><Link href={`/book?service=${service.id}`} className="button button--light">Choose this offering <span>↗</span></Link></section></main>
}
